name: build
on: push
jobs:
  build-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: husnimun/example-protocgen-go
          path: example-protocgen-go
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.18'
      - run: sudo apt-get install -y protobuf-compiler
      - run: go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
      - run: go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2
      - run: rm -rf example-protocgen-go/todo
      - run: >
          protoc --go_out=./example-protocgen-go --go_opt=paths=source_relative
          --go-grpc_out=./example-protocgen-go --go-grpc_opt=paths=source_relative
          todo/todo.proto
      - run: |
          cd example-protocgen-go
          go mod tidy
          git config user.name "Husni Munaya"
          git config user.email husnimun@gmail.com
          git add .
          git commit -m "generated"
      - name: push
        uses: cpina/github-action-push-to-another-repository@v1.4.2
        env:
          API_TOKEN_GITHUB: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          source-directory: 'example-protocgen-go'
          destination-github-username: 'husnimun'
          destination-repository-name: 'example-protocgen-go'
          user-email: husnimun@gmail.com
          target-branch: master
