name: test
on: [push]
jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.18'
      - run: sudo apt-get install -y protobuf-compiler
      - run: go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
      - run: go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2
      - run: >
          protoc --go_out=. --go_opt=paths=source_relative
          --go-grpc_out=. --go-grpc_opt=paths=source_relative
          todo/todo.proto
